"""description

Revision ID: 13777e9d7536
Revises: 5e542fde4a6d
Create Date: 2023-02-25 22:39:45.322099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13777e9d7536'
down_revision = '5e542fde4a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
