"""empty message

Revision ID: aebbf978e072
Revises: 5bb8d9841efd
Create Date: 2023-02-26 19:23:56.306663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aebbf978e072'
down_revision = '5bb8d9841efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods', schema=None) as batch_op:
        batch_op.alter_column('number_stock',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods', schema=None) as batch_op:
        batch_op.alter_column('number_stock',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
